sources:
  npm: true

allowed:
  - apache-2.0
  - 0bsd
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - blueoak-1.0.0

ignored:
  npm:
    # The source repository for this package has been deleted: http://github.com/substack/node-buffers.git
    - buffers
    # The source repository for this package has been deleted: http://github.com/substack/node-chainsaw.git
    - chainsaw
    - "@bufbuild/protobuf"
    - "@actions/http-client"
    - "@protobuf-ts/plugin-framework"
